# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Documentation',   url: 'documentation'}
- {name: 'Project',  url: 'project'}
- {name: 'Note',  url: 'note'}
- {name: 'About',  url: 'about'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/'}
- {icon: 'facebook', link:   'https://www.facebook.com/'}
- {icon: 'instagram', link:  'https://instagram.com/'}
- {icon: 'envelope', link:   'mailto:'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: '新着 Newer'
  previous_page: '過去 Older'

sharing_button_prompt: '共有する Feel free to share!'

related_posts: 'おすすめ You may also enjoy...'

post_date_prefix: 'Written on'
